services:
  - type: web
    name: my-web-service
    env: ruby
    plan: starter
    buildCommand: "bundle install && bundle exec rake db:migrate"
    startCommand: "bundle exec rails server -p $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
